export const specialityData = [
  {
    speciality: 'General physician',
    description: 'Comprehensive medical care for everyday health needs and diagnosis.',
    iconName: 'Stethoscope',
  },
  {
    speciality: 'Gynecologist',
    description: "Specialized care for women's reproductive health and wellness.",
    iconName: 'HeartPulse',
  },
  {
    speciality: 'Dermatologist',
    description: 'Expert treatment for skin, hair, nail conditions and skincare.',
    iconName: 'Sparkles',
  },
  {
    speciality: 'Pediatricians',
    description: 'Compassionate healthcare dedicated to infants, children, and teens.',
    iconName: 'Baby',
  },
  {
    speciality: 'Neurologist',
    description: 'Advanced diagnosis and treatment for nervous system disorders.',
    iconName: 'Activity',
  },
  {
    speciality: 'Gastroenterologist',
    description: 'Digestive system health and gastrointestinal disorder specialists.',
    iconName: 'ShieldCheck',
  },
];

export const doctorsData = [
  {
    _id: 'doc1',
    name: 'Dr. James Wilson',
    email: 'dr.james@mediqo.com',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=600&auto=format&fit=crop&q=80',
    speciality: 'General physician',
    degree: 'MBBS, MD (General Medicine)',
    experience: '12 Years',
    fees: 100,
    address: 'Mediqo Care Center, 742 Evergreen Ave, New York, NY',
    about: 'Dr. James Wilson is dedicated to providing holistic preventive medical care, early diagnosis, and tailored treatment plans for long-term health.',
    available: true,
  },
  {
    _id: 'doc2',
    name: 'Dr. Sarah Johnson',
    email: 'dr.sarah@mediqo.com',
    image: 'https://images.unsplash.com/photo-1594824813566-78a9c39ce425?w=600&auto=format&fit=crop&q=80',
    speciality: 'Gynecologist',
    degree: 'MBBS, MS (Obstetrics & Gynecology)',
    experience: '8 Years',
    fees: 120,
    address: 'Mediqo Health Plaza, 100 Harvard Ave, Boston, MA',
    about: 'Dr. Sarah Johnson provides compassionate gynecological care, prenatal counseling, and wellness screenings tailored for every stage of life.',
    available: true,
  },
  {
    _id: 'doc3',
    name: 'Dr. Emily Carter',
    email: 'dr.emily@mediqo.com',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&auto=format&fit=crop&q=80',
    speciality: 'Dermatologist',
    degree: 'MBBS, MD (Dermatology)',
    experience: '6 Years',
    fees: 110,
    address: 'Mediqo Skin & Wellness, 500 Market St, San Francisco, CA',
    about: 'Dr. Emily Carter specializes in medical dermatology, acne management, allergy testing, and therapeutic skin revitalization.',
    available: true,
  },
  {
    _id: 'doc4',
    name: 'Dr. Michael Brown',
    email: 'dr.michael@mediqo.com',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=600&auto=format&fit=crop&q=80',
    speciality: 'Pediatricians',
    degree: 'MBBS, DCH, MD (Pediatrics)',
    experience: '10 Years',
    fees: 100,
    address: 'Mediqo Pediatric Clinic, 250 Michigan Ave, Chicago, IL',
    about: 'Dr. Michael Brown focuses on pediatric development, routine vaccinations, and gentle childhood health management.',
    available: true,
  },
  {
    _id: 'doc5',
    name: 'Dr. Olivia Taylor',
    email: 'dr.olivia@mediqo.com',
    image: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=600&auto=format&fit=crop&q=80',
    speciality: 'Neurologist',
    degree: 'MBBS, DM (Neurology)',
    experience: '9 Years',
    fees: 140,
    address: 'Mediqo Neuroscience Institute, 800 Peachtree St, Atlanta, GA',
    about: 'Dr. Olivia Taylor brings clinical precision to neurological evaluations, headache treatments, and nerve health care.',
    available: true,
  },
  {
    _id: 'doc6',
    name: 'Dr. David Miller',
    email: 'dr.david@mediqo.com',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=600&auto=format&fit=crop&q=80',
    speciality: 'Gastroenterologist',
    degree: 'MBBS, DM (Gastroenterology)',
    experience: '11 Years',
    fees: 130,
    address: 'Mediqo Medical Center, 1200 Grand Ave, Los Angeles, CA',
    about: 'Dr. David Miller provides comprehensive digestive system evaluations and endoscopic expertise for gut health.',
    available: true,
  },
];

