export const specialityData = [
  {
    speciality: 'General physician',
    description: 'Comprehensive medical care for everyday health needs and diagnosis.',
    iconName: 'Stethoscope',
  },
  {
    speciality: 'Gynecologist',
    description: "Specialized care for women's reproductive health and wellness.",
    iconName: 'HeartPulse',
  },
  {
    speciality: 'Dermatologist',
    description: 'Expert treatment for skin, hair, nail conditions and skincare.',
    iconName: 'Sparkles',
  },
  {
    speciality: 'Pediatricians',
    description: 'Compassionate healthcare dedicated to infants, children, and teens.',
    iconName: 'Baby',
  },
  {
    speciality: 'Neurologist',
    description: 'Advanced diagnosis and treatment for nervous system disorders.',
    iconName: 'Activity',
  },
  {
    speciality: 'Gastroenterologist',
    description: 'Digestive system health and gastrointestinal disorder specialists.',
    iconName: 'ShieldCheck',
  },
];

export const doctorsData = [
  {
    _id: 'doc1',
    name: 'Dr. Richard James',
    email: 'dr.richard@mediqo.com',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=600&auto=format&fit=crop&q=80',
    speciality: 'General physician',
    degree: 'MBBS, MD',
    experience: '4 Years',
    fees: 50,
    address: '17th Cross, Richmond Circle, London',
    about: 'Dr. Richard James is dedicated to providing holistic preventive medical care, early diagnosis, and tailored treatment plans for long-term health.',
    available: true,
  },
  {
    _id: 'doc2',
    name: 'Dr. Emily Larson',
    email: 'dr.emily@mediqo.com',
    image: 'https://images.unsplash.com/photo-1594824813566-78a9c39ce425?w=600&auto=format&fit=crop&q=80',
    speciality: 'Gynecologist',
    degree: 'MBBS, MS',
    experience: '3 Years',
    fees: 60,
    address: '27th Cross, Richmond Circle, London',
    about: 'Dr. Emily Larson provides compassionate gynecological care, prenatal counseling, and wellness screenings tailored for every stage of life.',
    available: true,
  },
  {
    _id: 'doc3',
    name: 'Dr. Sarah Patel',
    email: 'dr.sarah@mediqo.com',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&auto=format&fit=crop&q=80',
    speciality: 'Dermatologist',
    degree: 'MBBS, MD (Dermatology)',
    experience: '1 Year',
    fees: 30,
    address: '37th Cross, Richmond Circle, London',
    about: 'Dr. Sarah Patel specializes in medical dermatology, acne management, allergy testing, and therapeutic skin revitalization.',
    available: true,
  },
  {
    _id: 'doc4',
    name: 'Dr. Christopher Lee',
    email: 'dr.lee@mediqo.com',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=600&auto=format&fit=crop&q=80',
    speciality: 'Pediatricians',
    degree: 'MBBS, DCH',
    experience: '2 Years',
    fees: 40,
    address: '47th Cross, Richmond Circle, London',
    about: 'Dr. Christopher Lee focuses on pediatric development, routine vaccinations, and gentle childhood health management.',
    available: true,
  },
  {
    _id: 'doc5',
    name: 'Dr. Jennifer Garcia',
    email: 'dr.garcia@mediqo.com',
    image: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=600&auto=format&fit=crop&q=80',
    speciality: 'Neurologist',
    degree: 'MBBS, DM (Neurology)',
    experience: '4 Years',
    fees: 50,
    address: '57th Cross, Richmond Circle, London',
    about: 'Dr. Jennifer Garcia brings clinical precision to neurological evaluations, headache treatments, and nerve health care.',
    available: true,
  },
  {
    _id: 'doc6',
    name: 'Dr. Andrew Williams',
    email: 'dr.williams@mediqo.com',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=600&auto=format&fit=crop&q=80',
    speciality: 'Gastroenterologist',
    degree: 'MBBS, DM',
    experience: '5 Years',
    fees: 55,
    address: '67th Cross, Richmond Circle, London',
    about: 'Dr. Andrew Williams provides comprehensive digestive system evaluations and endoscopic expertise for gut health.',
    available: true,
  },
];
